#! /usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);
my $event;

foreach (qw(
       /etc/ipsec.conf
       /etc/ipsec.d/xl2tpd.conf
       /etc/ipsec.d/xl2tpd.secrets
    ))
{
    templates2events("$_", qw(
    post-upgrade
    console-save
    bootstrap-console-save
    remoteaccess-update
    ipsec-update
    ));
}

#--------------------------------------------------
# actions for ipsec-update event
#--------------------------------------------------

event_link("ipsec-update", $event, "11");

# Runlevel init links.
service_link_enhanced("xl2tpd", "S95", "7");
service_link_enhanced("xl2tpd", "K21", "6");
service_link_enhanced("xl2tpd", "K21", "0");
service_link_enhanced("xl2tpd", "K21", "1");

safe_symlink("adjust", "root/etc/e-smith/events/$event/services2adjust/masq");
