#! /usr/bin/perl -w

# Need some thought on when the templates should be expanded and when the action should be called.

# Need to 

# On ipsec-update expand xl2tpd.conf & secrets


# On ip-up.xl2tpd expand and restart masq

use esmith::Build::CreateLinks qw(:all);


#--------------------------------------------------
# templates for events
#--------------------------------------------------



foreach (qw(
       /etc/ipsec.d/xl2tpd.conf
       /etc/ipsec.d/xl2tpd.secrets
       /etc/pam.d/ppp
       /etc/ppp/ip-up.local
       /etc/ppp/options.xl2tpd
       /etc/ppp/pap-secrets
       /etc/xl2tpd/xl2tpd.conf
    ))
{
    templates2events("$_", qw(
    post-upgrade
    console-save
    bootstrap-console-save
    remoteaccess-update
    ipsec-update
    ));
}

#--------------------------------------------------
# actions for ipsec-update event
#--------------------------------------------------

my $eventIpsec = "ipsec-update";

#--------------------------------------------------
# actions for ip-up.xl2tpd event
#--------------------------------------------------

my $eventXl2tpd = "ip-up.xl2tpd";

# What was I thinking here ? Should be $eventIpsec or my $eventXl2tpd
safe_symlink("adjust", "root/etc/e-smith/events/$eventXl2tpd/services2adjust/masq");

event_link("xl2tpd-interface-access", $eventXl2tpd, "70");

# Runlevel init links.
service_link_enhanced("xl2tpd", "S95", "7");
service_link_enhanced("xl2tpd", "K21", "6");
service_link_enhanced("xl2tpd", "K21", "0");
service_link_enhanced("xl2tpd", "K21", "1");

